---
- name: Добавляем репозитарий Nginx
  become: true
  become_method: sudo

  apt_repository:
    repo: ppa:ondrej/nginx

- name: Устанавливаем Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Замена конфига Nginx-Proxy
  template: "src=../templates/server-proxy.conf dest=/etc/nginx/nginx.conf owner=ubuntu group=ubuntu mode=0644"
  notify: restart nginx

- name: Запуск Nginx-Proxy
  # become: yes
  service:
    name: nginx
    state: started